-- ===================================================================
-- V2: Refresh-token versioning, refresh-token denylist, password reset
-- ===================================================================

-- Bumping token_version invalidates every access & refresh token a user
-- holds (used by logout-all, change-password, and password reset).
ALTER TABLE users ADD COLUMN token_version INTEGER NOT NULL DEFAULT 0;

-- Denylist of individual refresh-token IDs (the JWT "jti" claim). Used for
-- single-device logout and for detecting reuse of a rotated refresh token.
-- Rows are purged after expires_at by a scheduled cleanup task.
CREATE TABLE revoked_refresh_tokens (
    jti        VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    revoked_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_revoked_refresh_tokens PRIMARY KEY (jti)
);

CREATE INDEX idx_revoked_refresh_tokens_expires_at ON revoked_refresh_tokens (expires_at);

-- Single-use, time-limited tokens emailed for the "forgot password" flow.
CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT       NOT NULL,
    expires_at  TIMESTAMP    NOT NULL,
    used_at     TIMESTAMP,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_password_reset_tokens_token UNIQUE (token),
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);
